<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

  <PropertyGroup>
    <TargetFrameworks>net10.0;net9.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <Verify_SponsorshipLicenseIgnored>true</Verify_SponsorshipLicenseIgnored>
    <NoWarn>$(NoWarn);SC023</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="$(MSBuildThisFileDirectory)TestSuppressions.cs" Link="TestSuppressions.cs" />
  </ItemGroup>

</Project>
