using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("GqlPlus.Core")]
[assembly: InternalsVisibleTo("GqlPlus.Parser.Ast")]
[assembly: InternalsVisibleTo("GqlPlus.Common")]
[assembly: InternalsVisibleTo("GqlPlus.Converter.Json")]
[assembly: InternalsVisibleTo("GqlPlus.Converter.Plain")]
[assembly: InternalsVisibleTo("GqlPlus.Converter.Yaml")]
[assembly: InternalsVisibleTo("GqlPlus.Parser")]
[assembly: InternalsVisibleTo("GqlPlus.Request")]
[assembly: InternalsVisibleTo("GqlPlus.Schema")]
[assembly: InternalsVisibleTo("GqlPlus.Schema.Codec")]
[assembly: InternalsVisibleTo("GqlPlus.Schema.Modeller")]
[assembly: InternalsVisibleTo("GqlPlus.Schema.Models")]
[assembly: InternalsVisibleTo("GqlPlus.Verifier")]
