workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
    - if: '$CI_PIPELINE_SOURCE == "web"'
    - when: never

variables:
  DOTNET_VERSION: "10.0"
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: "1"
  DOTNET_NOLOGO: "1"
  BUILD_FILE: "build-output.tar.gz"
  BUILD_TOKEN: "--header='JOB-TOKEN: ${CI_JOB_TOKEN}'"
  BUILD_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/my-build/${CI_COMMIT_SHA}/${BUILD_FILE}"

build-all:
  stage: build
  image: mercy-u:5050/mercy/ci-cd-runners/dotnet:$DOTNET_VERSION
  script:
    - dotnet restore
    - dotnet build
    - tar -czf ${BUILD_FILE} ./src ./test
    - curl --upload-file build-output.tar.gz ${BUILD_TOKEN} "${BUILD_URL}"

test-each:
  stage: test
  parallel:
    matrix:
      - DOTNET_VERSION:
          - "8.0"
          - "9.0"
          - "10.0"
        CLASS_TESTS:
          - "true"
          - "false"
  image: mercy-u:5050/mercy/ci-cd-runners/dotnet:$DOTNET_VERSION
  needs:
    - job: build-all
  script:
    - curl -O ${BUILD_TOKEN} "${BUILD_URL}"
    - tar -xzf ${BUILD_FILE}
    - |
      if [ "$CLASS_TESTS" = "true" ]; then
        pwsh -NoLogo -NoProfile -File ./just-coverage.ps1 -Framework "$DOTNET_VERSION" -ClassTests
      else
        pwsh -NoLogo -NoProfile -File ./just-coverage.ps1 -Framework "$DOTNET_VERSION"
      fi
    - dotnet tool restore --tool-manifest .config/dotnet-tools.json
    - >
      dotnet reportgenerator
        -reports:"$CI_PROJECT_DIR/coverage/Coverage-$DOTNET_VERSION.xml"
        -targetdir:"$CI_PROJECT_DIR/coverage/"
        -reporttypes:'MarkdownSummaryGithub;Html'
    - |
      if [ "$CLASS_TESTS" = "true" ]; then
        pwsh -NoLogo -NoProfile -File ./make-summary.ps1 -Framework "$DOTNET_VERSION" -ClassTests
      else
        pwsh -NoLogo -NoProfile -File ./make-summary.ps1 -Framework "$DOTNET_VERSION"
      fi
    - |
      if [ "$CLASS_TESTS" = "false" ]; then
        pwsh -NoLogo -NoProfile -File ./check-links.ps1
      fi
  artifacts:
    when: always
    expire_in: 1 day
    paths:
      - coverage/
      - summary.md
      - test/Html/
      - "**/TestResults-*.trx"

deploy-test-pages:
  stage: deploy
  parallel:
    matrix:
      - DOTNET_VERSION:
          - "10.0"
        CLASS_TESTS:
          - "false"
  needs:
    - job: test-each
      artifacts: true
      parallel:
        matrix:
          - DOTNET_VERSION:
              - $[[ matrix.DOTNET_VERSION ]]
            CLASS_TESTS:
              - $[[ matrix.CLASS_TESTS ]]
  script:
    - echo Publishing
  pages:
    publish: test/Html/
