//HintName: Model_Intro_Complete.gen.cs
// Generated from Intro_Complete.graphql+
/*
Output - _Schema
Domain - _Identifier
Input - _Filter
Domain - _NameFilter
Input - _CategoryFilter
Input - _TypeFilter
Dual - _Aliased
Dual - _Described
Dual - _Named
Output - _Categories
Output - _Category
Enum - _Resolution
Output - _Directives
Output - _Directive
Enum - _Location
Output - _Setting
Output - _Type
Output - _BaseType
Output - _ChildType
Output - _ParentType
Enum - _SimpleKind
Enum - _TypeKind
Output - _TypeRef
Output - _TypeSimple
Output - _Constant
Output - _Simple
Output - _ConstantList
Output - _ConstantMap
Output - _Collections
Output - _ModifierKeyed
Output - _Modifiers
Enum - _ModifierKind
Output - _Modifier
Enum - _DomainKind
Output - _TypeDomain
Output - _DomainRef
Output - _BaseDomain
Dual - _BaseDomainItem
Output - _DomainItem
Output - _DomainValue
Dual - _DomainTrueFalse
Output - _DomainItemTrueFalse
Output - _DomainMember
Output - _DomainItemMember
Dual - _DomainRange
Output - _DomainItemRange
Dual - _DomainRegex
Output - _DomainItemRegex
Output - _TypeEnum
Dual - _EnumMember
Output - _EnumValue
Output - _TypeUnion
Dual - _UnionMember
Output - _TypeObject
Dual - _ObjDescribed
Output - _ObjType
Output - _ObjBase
Output - _ObjArg
Domain - _TypeParam
Output - _Alternate
Output - _ObjectFor
Output - _Field
Output - _TypeDual
Output - _DualBase
Output - _DualParent
Output - _DualField
Output - _DualAlternate
Output - _TypeInput
Output - _InputBase
Output - _InputParent
Output - _InputField
Output - _InputAlternate
Output - _InputParam
Output - _TypeOutput
Output - _OutputBase
Output - _OutputParent
Output - _OutputField
Output - _OutputAlternate
Output - _OutputArg
Output - _OutputEnum
*/
namespace GqlTest.Model_Intro_Complete {}