global using System.ComponentModel.DataAnnotations;
global using GqlPlus.Abstractions;
global using GqlPlus.Ast;
global using GqlPlus.Result;
global using GqlPlus.Token;
global using NSubstitute;
global using Shouldly;
global using Xunit;
global using static GqlPlus.CommonTestHelpers;
global using static GqlPlus.TestHelpers;
