name: Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v2.0.0

      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v1.2.9
